name: CD Node.js Auth Server with docker

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # 저장소에서 코드 체크아웃
    - uses: actions/checkout@v4

    # Github Actions VM에 Docker 설치
    - name: Docker Setup Docker
      uses: docker/setup-docker-action@v4.0.0

    # 환경 파일 생성
    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_FILE }}" | base64 -d > .dockerenv
        
    # Docker Hub에 로그인
    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # 이미지 빌드, Docker Hub에 push
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.10.0
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/auth-server:${{ github.sha }}

    # SSH를 사용하여 클라우드에 배포
    - name: Deploy to Cloud
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # 기존 컨테이너 제거
          sudo docker stop auth-server || true
          docker rm auth-server || true

          # Docker Hub에서 최신 이미지 pull
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/auth-server:${{ github.sha }}

          # 새 컨테이너 실행
          sudo docker run -d \
            --name auth-server \
            -p 5555:5555 \
             ${{ secrets.DOCKER_USERNAME }}/auth-server:${{ github.sha }}
            
        
